### ISSUE TITLE
Pre-validation error in stimela 2.0rc4 for keyword 'UNSET'

### ISSUE THREAD

**Issue by Victoria-Samboco** [caracal-pipeline/stimela2#157] opened 2023-05-12 12:42 UTC
I encounter a prevalidation error while trying to run a recipe in Stimela (version 2.0rc4). The error message indicates that two steps in the recipe, 'clean_image_sun' and 'quality_control_imaging', failed prevalidation due to an invalid auto-threshold value of UNSET. I am trying to figure out how to fix this error and would appreciate any assistance.

```2023-05-12 14:23:27 STIMELA INFO: pre-validating the recipe
2023-05-12 14:23:28 STIMELA ERROR: prevalidation of recipe 'boom' failed
──────────────────────────── detailed error report follows ─────────────────────────────
        ⚠ prevalidation of recipe 'boom' failed
        └── recipe 'boom': 2 errors
            ├── step 'clean_image_sun' failed prevalidation
            │   └── step 'image' failed prevalidation
            │       └── 1 parameter(s) failed validation:
            │           └── auto-threshold = UNSET: value is not a valid float
            └── step 'quality_control_imaging' failed prevalidation
                └── step 'image' failed prevalidation
                    └── 1 parameter(s) failed validation:
                        └── auto-threshold = UNSET: value is not a valid float
```
Also, I would like to let you know that I encountered this error after upgrading from Stimela version 2.0rc2, which did not produce this error. I had to do it to match the new version of quartical, but now it returns this error.

**Comment by o-smirnov** [comment] 2023-05-12 14:50
Replace "UNSET" with "=UNSET" in your recipe.

It was never supposed to recognize plain "UNSET" without "=", but due to a bug, it did... bug's now fixed...

**Comment by Victoria-Samboco** [comment] 2023-05-12 16:01
> Replace "UNSET" with "=UNSET" in your recipe.
> 
> It was never supposed to recognize plain "UNSET" without "=", but due to a bug, it did... bug's now fixed...
>
This is funny because I also found a way to eliminate the error by adding the parameter to the wsclean cab in my main recipe and defining ```dtype``` as ```str```  and it stopped returning the error, but when I run wsclean with that parameter it does not recognize the parameter anyway. 
 
Adding "=" fixed the problem, thank you.

**Comment by o-smirnov** [comment] 2023-05-15 10:50
Yeah that all worked as designed then -- in the standard cab, the parameter has a ``float`` type, while plain "UNSET" is treated as a string, and so causes a validation error when matched to a float. You overrode the definition with a ``str`` type, so now the validation worked, but of course wsclean still expects a float, so the error happens down the line.

**Closed as completed** 2023-06-28 19:39 UTC
